export const allProducts = [
    {
      "id": 64,
      "product_uuid": "PD8f252e5a-0ac0-41c1-9ff0-c0a2107e9d29",
      "name": "Ryco Air Filter A1408",
      "retail_price": 70.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 63,
      "product_uuid": "PD43816056-2c91-4db9-a7b7-88c526554ad2",
      "name": "Ryco Air Filter A1512",
      "retail_price": 101.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 65,
      "product_uuid": "PD1d3fd0d4-5948-49c0-9280-e7632dd2fefb",
      "name": "Ryco Air Filter A1241",
      "retail_price": 27.12,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 62,
      "product_uuid": "PDc412ae3a-1514-4423-a6b8-5ab36542cb9e",
      "name": "Ryco Air Filter A1523",
      "retail_price": 63.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 61,
      "product_uuid": "PDf635d6bc-78f9-4854-847c-6867de4376a1",
      "name": "Ryco Air Filter A1524",
      "retail_price": 77.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 60,
      "product_uuid": "PDd5ff60f7-8601-48cf-b0ef-968debc7e46d",
      "name": "Ryco Air Filter A1629",
      "retail_price": 77.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 59,
      "product_uuid": "PDf0a4da8d-d316-4534-b221-855f909f8ea7",
      "name": "Ryco Air Filter A1785",
      "retail_price": 63.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 58,
      "product_uuid": "PDd62417ba-8656-4657-b50a-3f85b63bc09d",
      "name": "Ryco Air Filter A1806",
      "retail_price": 71.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 57,
      "product_uuid": "PD38cbe3d0-3883-42db-a5a3-f5f844c12dd2",
      "name": "Ryco Air Filter A1800",
      "retail_price": 63.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 56,
      "product_uuid": "PDe59041aa-ba8e-4661-933a-c3aad126ace9",
      "name": "Ryco Air Filter A1811",
      "retail_price": 96.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 54,
      "product_uuid": "PD132c96ef-42e1-4ced-ae13-a8e379102a47",
      "name": "Ryco Air Filter A1490",
      "retail_price": 83.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 77,
      "product_uuid": "PD091d288b-7695-4b73-a632-20a9c9586b15",
      "name": "Koba Battery MF55B24L",
      "retail_price": 174.87,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 78,
      "product_uuid": "PDa9823582-8dae-491e-b9a7-85ca1b052efa",
      "name": "Koba Battery MF55B24R",
      "retail_price": 174.87,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 79,
      "product_uuid": "PD7bf38fb7-5d20-4cd1-abe8-db79b4c0eb16",
      "name": "Koba Battery MF75D23FR",
      "retail_price": 234.25,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 80,
      "product_uuid": "PD3de344b7-0805-4f2d-abe5-970c69cac5b4",
      "name": "Koba Battery MF75D23FL",
      "retail_price": 234.25,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 81,
      "product_uuid": "PD0e3c8e4d-6447-4992-a890-0dc5daa3abb2",
      "name": "Koba Battery MF54321",
      "retail_price": 186.01,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 82,
      "product_uuid": "PD2ac211da-7752-4a7b-8a0e-de80f43d4686",
      "name": "Koba Battery MF57412",
      "retail_price": 268.15,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 83,
      "product_uuid": "PDa694a0fd-6c3c-48cd-b851-6d83c7d8c027",
      "name": "Koba Battery MF57113",
      "retail_price": 261.18,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 84,
      "product_uuid": "PD3bd7caeb-b543-4832-a6b8-f091a72d46b1",
      "name": "Koba Battery MF95D31FR",
      "retail_price": 324.63,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 85,
      "product_uuid": "PDa98ee50c-fa81-49f5-9bc7-a61664b71fac",
      "name": "Koba Battery MF57539",
      "retail_price": 296.28,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 75,
      "product_uuid": "PDcfc604ca-8e27-49be-a4ff-0b7ab72e0346",
      "name": "Koba Battery MF60038",
      "retail_price": 360.7,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 66,
      "product_uuid": "PD72f98205-6062-45db-9478-248982a3d525",
      "name": "Koba Battery MF80D26FL",
      "retail_price": 242.89,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 67,
      "product_uuid": "PDb7c2ca68-7b26-4ca6-9198-b3738e249fa8",
      "name": "Koba Battery MF80D26FR",
      "retail_price": 242.89,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 68,
      "product_uuid": "PDc9817481-881d-45eb-b760-c9fbb128ea9e",
      "name": "Koba Battery MF22F-550",
      "retail_price": 197.42,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 69,
      "product_uuid": "PDffffcb23-f4c4-429a-862f-6a5543c428db",
      "name": "Koba Battery MF22FR-550",
      "retail_price": 197.42,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 70,
      "product_uuid": "PD55d9abb1-97ec-4834-9972-b8693b32010f",
      "name": "Koba Battery MF40B19L",
      "retail_price": 143.82,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 71,
      "product_uuid": "PDd3186d63-7c66-439a-8eb3-803fef3f1b02",
      "name": "Koba Battery MF40B19R",
      "retail_price": 143.82,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 72,
      "product_uuid": "PDb730518f-68a5-4169-a6ac-c43a941a03eb",
      "name": "Koba Battery MF55457",
      "retail_price": 205.47,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 73,
      "product_uuid": "PDf5b077a8-cfde-4dd2-950a-630b31ee76c5",
      "name": "Koba Battery MF56219",
      "retail_price": 222.21,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 74,
      "product_uuid": "PD5607970b-511d-482d-a63d-a5ce74961766",
      "name": "Koba Battery SEM42R",
      "retail_price": 197.6,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 76,
      "product_uuid": "PD9394e8bc-4101-4289-a079-944098a04e50",
      "name": "Koba Battery MF58515",
      "retail_price": 312.14,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Battery",
      "brand_display": "Koba"
    },
    {
      "id": 131,
      "product_uuid": "PDa737f123-9be3-4a08-bef2-8e47fa1c151a",
      "name": "Anti-Squeal Brake Treatment",
      "retail_price": 0.78,
      "quantity": 5,
      "set_quantity_in_mechanic_screen": true,
      "productphoto_set": [],
      "product_type_display": "Brake Accessories",
      "brand_display": "Wurth"
    },
    {
      "id": 106,
      "product_uuid": "PD0e50627e-a57c-4c87-8b6f-b01a3e6e96ff",
      "name": "Wurth Brake Clean",
      "retail_price": 20.64,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": true,
      "productphoto_set": [],
      "product_type_display": "Brake Accessories",
      "brand_display": "Wurth"
    },
    {
      "id": 107,
      "product_uuid": "PDfb28bb61-34d0-46b0-9678-c4404d7cfdb9",
      "name": "Wurth Brake Protection Paste",
      "retail_price": 0.96,
      "quantity": 5.5,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Brake Accessories",
      "brand_display": "Wurth"
    },
    {
      "id": 55,
      "product_uuid": "PDc7e068f2-5ae4-4793-9e38-28b239456bcb",
      "name": "Ryco Cabin Air Filter RCA119M",
      "retail_price": 71.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Cabin Air Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 50,
      "product_uuid": "PD05e2da92-7fe1-4ae6-a384-c08bf7c7a9c1",
      "name": "Ryco Cabin Filter RCA227P",
      "retail_price": 48.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Cabin Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 49,
      "product_uuid": "PD33d4adee-a7ab-4ef1-9e91-87ef4dff7281",
      "name": "Ryco Cabin Filter RCA248P",
      "retail_price": 40.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Cabin Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 48,
      "product_uuid": "PDe73171cc-c5ef-4962-8837-a1080a4edd30",
      "name": "Ryco Cabin Filter RCA275P",
      "retail_price": 84.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Cabin Filter",
      "brand_display": "Ryco"
    },
    {
      "id": 51,
      "product_uuid": "PD84c9306c-7e25-4773-9980-29dce3a18214",
      "name": "Ryco Cabin Filter RCA232P",
      "retail_price": 70.9,
      "quantity": 1,
      "set_quantity_in_mechanic_screen": false,
      "productphoto_set": [],
      "product_type_display": "Cabin Filter",
      "brand_display": "Ryco"
    }
  ]